service: import-service

frameworkVersion: "2"

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-aws-documentation

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    uploadBucket: products-upload-bucket
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::products-upload-bucket/*"

functions:
  importProductFile:
    handler: src/handlers/index.importProductFileHandler
    events:
      - http:
          path: import
          method: get
          cors: true
  importFileParser:
    handler: src/handlers/index.importFileParserHandler
    events:
      - s3:
          bucket: products-upload-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded
          existing: true
