service: import-service

frameworkVersion: "2"

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  sqsName: catalogItemsQueue

plugins:
  - serverless-webpack
  - serverless-aws-documentation
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    uploadBucket: products-upload-bucket
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::products-upload-bucket/*"
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
      Resource: "arn:aws:sqs:#{AWS::Region}:#{AWS::AccountId}:${self:custom.sqsName}"

functions:
  importProductFile:
    handler: src/handlers/index.importProductFileHandler
    events:
      - http:
          path: import
          method: get
          cors: true
          authorizer:
            name: requestAuthorizer
            identitySource: method.request.header.Authorization
            type: token
            resultTtlInSeconds: 0
            arn: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:authorization-service-dev-basicAuthorizer"
  importFileParser:
    handler: src/handlers/index.importFileParserHandler
    events:
      - s3:
          bucket: products-upload-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded
          existing: true
    environment:
      sqsUrl: "https://sqs.#{AWS::Region}.amazonaws.com/#{AWS::AccountId}/${self:custom.sqsName}"

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: "ApiGatewayRestApi"
