---
swagger: "2.0"
info:
  description: "Products API for NodeJS AWS GMP"
  version: "2021-04-06T20:03:08Z"
  title: "dev-product-service"
  contact:
    name: "Yahor Sheinikau"
    url: "https://github.com/naooki"
    email: "sheynikovea@gmail.com"
host: "uhvqepz8rb.execute-api.eu-west-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /products:
    get:
      summary: "Get Products"
      description: "Returns a list of porducts"
      produces:
      - "application/json"
      parameters:
      - name: "search"
        in: "query"
        description: "The string to search for in item titles"
        required: false
        type: "string"
      - name: "limit"
        in: "query"
        description: "The limit number of items to return"
        required: false
        type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/GetProductsResponse"
        "400":
          description: "400 response"
          schema:
            $ref: "#/definitions/ErrorResponse"
  /products/{productId}:
    get:
      summary: "Get Product By ID"
      description: "Returns a product by ID"
      produces:
      - "application/json"
      parameters:
      - name: "productId"
        in: "path"
        description: "The ID of the Product to find"
        required: true
        type: "string"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/GetProductResponse"
        "400":
          description: "400 response"
          schema:
            $ref: "#/definitions/ErrorResponse"
        "404":
          description: "404 response"
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  GetProductResponse:
    type: "object"
    properties:
      product:
        $ref: "#/definitions/Product"
      message:
        type: "string"
      statusCode:
        type: "integer"
    description: "Get Product Response Model"
  GetProductsResponse:
    type: "object"
    properties:
      product:
        type: "array"
        items:
          $ref: "#/definitions/Product"
      message:
        type: "string"
      statusCode:
        type: "integer"
    description: "Get Products Response Model"
  Product:
    type: "object"
    properties:
      price:
        type: "integer"
        description: "The price of a product"
      count:
        type: "integer"
        description: "The amount of products"
      description:
        type: "string"
        description: "The description of a product"
      id:
        type: "string"
        description: "The unique identifier for a product"
      title:
        type: "string"
        description: "The title of a product"
    title: "Product"
    description: "Product model"
  ErrorResponse:
    type: "object"
    properties:
      message:
        type: "string"
      statusCode:
        type: "integer"
    description: "Generic error response"
