service:
  name: product-service

frameworkVersion: '2'

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  lambdaHashingVersion: 20201221


functions:
  getProductById:
    handler: src/handlers/index.getProductByIdHandler
    events:
      - http:
          method: get
          path: products/{productId}
  getProductsList:
    handler: src/handlers/index.getProductsListHandler
    events:
      - http:
          method: get
          path: products
